events {
    worker_connections 1024;
}

http {
    # Membatasi request (Rate Limiting) untuk mencegah spam
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=5r/s;

    # Mendefinisikan grup server aplikasi (untuk Load Balancing)
    upstream web_backend {
        server web:5000;
    }

    server {
        listen 80;

        location / {
            # Menerapkan rate limit (maksimal 5 request per detik dari 1 IP)
            limit_req zone=mylimit burst=10 nodelay;

            # Meneruskan traffic ke grup aplikasi web
            proxy_pass http://web_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
